Repository danvergara/dblab, pull requests merged in 2024-06, with the labels that each got.

#201 Add oracle driver to support oracle databases
  Makefile
  README.md
  cmd/root.go
  docker-compose.yml
  go.mod
  go.sum
  pkg/client/client.go
  pkg/client/oracle.go
  pkg/command/command.go
  pkg/config/.dblab.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/connection/connection.go
  pkg/connection/connection_test.go
  pkg/drivers/drivers.go
  pkg/form/form.go
  pkg/form/form_test.go
  pkg/form/update.go
  pkg/form/view.go
Labels: kind/enhancement

#206 Fix a bug in README
  README.md
Labels: kind/docs

#213 fix Driver name
  pkg/connection/connection.go
Labels: kind/bugfix

#215 remove validation on sqlite database file extension
  pkg/connection/connection.go
  pkg/connection/connection_test.go
Labels: kind/bugfix

#221 add a new description on new query params supported due to the sqlite drive change
  Makefile
  README.md
  pkg/connection/connection.go
Labels: kind/docs, kind/bugfix

#219 Add a small improvement to the installation script
  scripts/install_update_linux.sh
  scripts/install_update_sqlite_linux.sh
Labels: kind/enhancement

#218 Fix typo
  docs/usage.md
Labels: kind/docs

#216 add pgup and pgdn to navigate through the resulsets
  README.md
  pkg/gui/keybindings.go
Labels: kind/enhancement
